print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Shogo/Projects/GiG/unknown/Assets/player.mb"`)
{		
	file -o "/Users/Shogo/Projects/GiG/unknown/Assets/player.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Shogo/Projects/GiG/unknown/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Shogo/Projects/GiG/unknown/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Shogo/Projects/GiG/unknown/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
